driverClassName=com.mysql.jdbc.Driver
url=jdbc:mysql://127.0.0.1:3306/spark?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
username=root
password=123456
initialSize=5
maxActive=10
maxWait=3000